version: 0.0
os: linux
files:
 - source: /
   destination: /home/ubuntu/storebridger-backend
permissions:
 - object: /home/ubuntu/storebridger-backend
   owner: ubuntu
   group: ubuntu
hooks:
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
